### ISSUE TITLE
Undefined property: stdClass::$balance

### ISSUE THREAD

**Issue by drizzersilverberg** [steevenz/rajasms#1]
version: 2.0

when executing $rajasms->send('my_username', 'my_secret_key'), an error occurs:

< HTTP/1.1 302 Found
< Date: Mon, 21 May 2018 04:59:21 GMT
< Server: Apache
< X-Powered-By: PHP/5.6.31
< Location: {{ hidden }}
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< Connection: Keep-Alive
< * Connection #0 to host {{ hidden}} left intact

PHP Notice:  Undefined property: stdClass::$balance in /home/vagrant/xxx/vendor/steevenz/rajasms/src/Rajasms.php on line 286

Notice: Undefined property: stdClass::$balance in /home/vagrant/xxx/vendor/steevenz/rajasms/src/Rajasms.php on line 286

@steevenz @steevenz @steevenz

**Comment by galpratama** [comment]
I also facing the same issues

I am using: 
"laravel/framework": "5.6.*",
"steevenz/rajasms": "^2.0",
"php": ">=7.1.3",

**Comment by steevenz** [comment]
Halo mohon maaf sebelumnya karena sudah lama tidak digunakan sepertinya ada perubahan API dari sistem mereka.. sy coba request nanti sy update
